"""Abstract playback backend (implemented by Flet video adapter)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class PlaybackPort(Protocol):
    async def play(self) -> None: ...
    async def pause(self) -> None: ...
    async def play_or_pause(self) -> None: ...
    async def is_playing(self) -> bool: ...
    async def seek_microseconds(self, position_us: int) -> None: ...
    async def get_position_us(self) -> int: ...
    async def get_duration_us(self) -> int: ...
    async def set_volume(self, level_0_100: float) -> None: ...
    async def set_playlist_uri(self, uri: str, autoplay: bool = True) -> None: ...
